language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r test-requirements.txt -r requirements.txt
  - pip install -e .
script:
    - nosetests --with-coverage --cover-package=eom tests
